const { createClient, AuthType } = require("webdav");

const category_map = [
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Safety",
	"bc_path":  ["Misc"] },                                       
{ "itemGroup": "", "type": "",
	"bc_path":  ["Misc"] },                                       
{ "itemGroup": "", "type": "Accessory - Light and Laser",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'BORESIGHTER MAGNETIC MULTI-CAL'} },
{ "itemGroup": "", "type": "Accessory - Parts",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'BYRNA BANSHEE ALARM 130DB'} },
{ "itemGroup": "", "type": "Accessory - Charging Handle",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'SLIDE ASY 320 PRO 9MM 3.6" COY'} },
{ "itemGroup": "", "type": "Accessory - Slide Assembly",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'SLIDE ASY 320 PRO 9MM 3.6" COY'} },
{ "itemGroup": "", "type": "Accessory-Actions",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Actions"] },                                         //itemNo: 'TAVOR X95 5.56MM CONVSN 16" RH'} },
{ "itemGroup": "", "type": "Accessory-Ammunition",
		"bc_path":  ["Firearms", "Shooting", "Ammunition"] },                                         //itemNo: 'AMMO 416BAR 452GR MTAC 80RD'} },
{ "itemGroup": "", "type": "Accessory-Barrels",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Barrels"] },                                         //itemNo: 'PPQ 9MM 4.6" THREADED BBL KIT'} },
{ "itemGroup": "", "type": "Accessory-Binoculars",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Binoculars"] },                                         //itemNo: 'ZULU 6 BINO 16X42 GRAPHITE'} },
{ "itemGroup": "", "type": "Accessory-Bipod",
		"bc_path":  ["Firearms", "Shooting", "Shooting Accessories", "Rests, Bipods & Tripods"] },                                         //itemNo: 'SKYLINE PRECISION BIPOD PIC'} },
{ "itemGroup": "", "type": "Accessory-Bolts",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'OPTIMIZED BOLT CARRIER 5.56'} },
{ "itemGroup": "", "type": "Accessory-Cases",
		"bc_path":  ["Firearms", "Shooting", "Storage & Security", "Gun Cases"] },                                         //itemNo: 'CASE FOR CRICKETT BLACK'} },
{ "itemGroup": "", "type": "Accessory-CO2 Cartridge",
		"bc_path":  ["Misc"] },                                         //itemNo: 'BYRNA 8 GRAM CO2 CARTRIDGES'} },
{ "itemGroup": "", "type": "Accessory-Flash Hiders",
		"bc_path":  ["Misc"] },                                         //itemNo: 'QUICKMOUNT 5.56MM CC FH 1/2-28'} },
{ "itemGroup": "", "type": "Accessory-Grips",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Grips"] },                                         //itemNo: 'GRIP ASY 365XL STANDARD COYOTE'} },
{ "itemGroup": "", "type": "Accessory-Handguard",
		"bc_path":  ["Misc"] },                                         //itemNo: 'HANDGUARD M400 TREAD ENH 10"'} },
{ "itemGroup": "", "type": "Accessory-Holsters",
		"bc_path":  ["Firearms", "Shooting", "Shooting Accessories", "Holsters"] },                                         //itemNo: 'SERPA CQC GLOCK 19/23/32/36'} },
{ "itemGroup": "", "type": "Accessory-Kits",
		"bc_path":  ["Misc"] },                                         //itemNo: 'SHADOW 2 KADET 22LR CONV KIT'} },
{ "itemGroup": "", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'EOTECH 550 MODEL 552 AA-BATTRY'} },
{ "itemGroup": "", "type": "Accessory-Lights",
		"bc_path":  ["Camping & Outdoors", "Lighting"] },                                         //itemNo: 'M600DF SCOUT LIGHT TAN 1500LM'} },
{ "itemGroup": "", "type": "Accessory-Lowers",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Lowers"] },                                         //itemNo: 'LOWER RECEIVER SCO15'} },
{ "itemGroup": "", "type": "Accessory-Magazine Pouches",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'DOUBLE STACK DOUBLE MAG CASE'} },
{ "itemGroup": "", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'PROMAG SKS 7.62X39 20RD POLY'} },
{ "itemGroup": "", "type": "Accessory-Muzzle Brakes",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Muzzle Brakes"] },                                         //itemNo: 'FLASH HIDER MINI QD 5/8-24'} },
{ "itemGroup": "", "type": "Accessory-Rails",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Rails"] },                                         //itemNo: 'MFR XL 9.0 KEYMOD ASSY BLK   #'} },
{ "itemGroup": "", "type": "Accessory-Range Finders",
		"bc_path":  ["Firearms", "Shooting", "Optics","Binoculars","Range Finders"] },                                         //itemNo: 'KILO8K-ABS 7X25MM LSR RNGFNDR'} },
{ "itemGroup": "", "type": "Accessory-Receiver Set",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'SIX8 RECEIVER SET 6.8SPC BLK'} },
{ "itemGroup": "", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases"] },                                         //itemNo: 'RINGS MAXIMA 30MM MED MT VERT'} },
{ "itemGroup": "", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'FREEDOM 4-12X40MM 1" CREEDMOOR'} },
{ "itemGroup": "", "type": "Accessory-Silencer Accessories",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'SANDMAN PYRO COMPENSATOR FH'} },
{ "itemGroup": "", "type": "Accessory-Slings and Swivels",
		"bc_path":  ["Firearms","Shooting","Shooting Accessories","Slings & Swivels"] },                                         //itemNo: 'SKYLINE SLING SWIVEL PIC RAIL'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Slings and Swivels",
		"bc_path":  ["Firearms","Shooting","Shooting Accessories","Slings & Swivels"] },                                         //itemNo: 'SKYLINE SLING SWIVEL PIC RAIL'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Slings and Swivels",
		"bc_path":  ["Firearms","Shooting","Shooting Accessories","Slings & Swivels"] },                                         //itemNo: 'SKYLINE SLING SWIVEL PIC RAIL'} },
{ "itemGroup": "", "type": "Accessory-Spotting Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'OSCAR 3 10-20X30 CMPT SPOT SCP'} },
{ "itemGroup": "", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Stocks"] },                                         //itemNo: 'MPX STOCK ADAPTER ASSEMBLY'} },
{ "itemGroup": "", "type": "Accessory-Tools",
		"bc_path":  ["Gear & Apparel", "Accessories", "Knives & Tools"] },                                         //itemNo: 'T-15 TORQUE WRENCH 25IN-LBS'} },
{ "itemGroup": "", "type": "Accessory-Trigger",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Triggers"] },                                         //itemNo: 'TRIGGER P320 FLAT BLACK'} },
{ "itemGroup": "", "type": "Accessory-Uppers",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Upper Receivers"] },                                         //itemNo: 'XM-15 QRC UPPER RECEIVER'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Uppers",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Upper Receivers"] },                                         //itemNo: 'XM-15 QRC UPPER RECEIVER'} },
{ "itemGroup": "", "type": "Combo",
		"bc_path":  ["Misc"] },                                         //itemNo: 'M6 12GA/22WMR BL/STL 18.5" O/U'} },
{ "itemGroup": "", "type": "Muzzleloader",
		"bc_path":  ["Firearms","Shooting","Black Powder","Muzzleloader"] },                                         //itemNo: 'PARAMOUNT HTR .40CAL CAMO 26"'} },
{ "itemGroup": "", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'SIDEWINDER 45ACP 578X28 BLACK'} },
{ "itemGroup": "", "type": "NFA - Short Barrel Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'GALIL ACE SBR 7.62X51 11.8"'} },
{ "itemGroup": "", "type": "Non-Lethal",
		"bc_path":  ["Firearms","Shooting","Safety & Protection", "Non Lethal Defense"] },                                         //itemNo: 'BYRNA HD KINETIC KIT ORANGE  #'} },
{ "itemGroup": "", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'MINI-MASTER 22MAG 4" AS'} },
{ "itemGroup": "", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'BIG BOY ALL-WEATHER 45LC'} },
{ "itemGroup": "", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'BUCKMARK FIELD TGT 22LR TG SR#'} },
{ "itemGroup": "", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns"] },                                         //itemNo: 'BPS FIELD MICRO MIDAS 20/24  #'} },
{ "itemGroup": "", "type": "Specialty Handgun",
		"bc_path":  ["Firearms", "Handguns"] },                                         //itemNo: 'MARES LEG 44MAG/44SPC BL/WD'} },
{ "itemGroup": "AR Style Centerfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'MR762 308WIN 16.5" 10+1 M-LOK'} },
{ "itemGroup": "AR Style Centerfire Rifles", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'DB15D PIST 5.56MM BRONZE 7"  #'} },
{ "itemGroup": "Binoculars", "type": "Accessory-Binoculars",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Binoculars"] },                                         //itemNo: 'BINO BX-1 MCKENZIE HD 8X42'} },
{ "itemGroup": "Black Powder Guns", "type": "Muzzleloader",
		"bc_path":  ["Firearms", "Shooting", "Black Powder", "Muzzleloader"] },                                         //itemNo: 'PURSUIT VAPR XT 50CAL SS/BLK'} },
{ "itemGroup": "Centerfire Pistol Silencers", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'OBSIDIAN45 45ACP SILENCR BLACK'} },
{ "itemGroup": "Centerfire Rifle Silencers", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'DD WAVE 7.62QD SILENCER 5/8-24'} },
{ "itemGroup": "Derringers", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'VP9/P30 MAG CONVERSION KIT'} },
{ "itemGroup": "Derringers", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms", "Handguns", "Derringers"] },                                         //itemNo: 'VP9 OR SLIDE WITH TALL SIGHTS'} },
{ "itemGroup": "Derringers", "type": "Rifle",
		"bc_path":  ["Firearms", "Handguns", "Derringers"] },                                         //itemNo: 'GSG-16 CARB 22LR BLK 10+1 16"'} },
{ "itemGroup": "Derringers", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Derringers"] },                                         //itemNo: 'FN 509 9MM FULL FDE 4" 10+1 FS'} },
{ "itemGroup": "Double Action Centerfire Revolvers", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: '500 500S&W MAG 3.5" SS AS 5RD'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'PROMAG GLK 42 380ACP MAG 10RD'} },
{ "itemGroup": "Double Action Centrfire Conceal Revolver", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'SP101 DELUXE 357MAG 2-1/4 SS'} },
{ "itemGroup": "Double Action Centerfire Revolvers", "type": "Rifle",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'CIRCUIT JUDGE 45LC/410 SND/BLK'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: '351PD 22MAG 1-7/8" 7RD HI-VIZ'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory - Parts",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'ARCHANGEL CHARGING HANDLE 308'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Lights",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'LASERGUARD S&W M&P 2.0 9MM/40'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'RAIL MASTER PRO RED LSR/LIGHT'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Grips",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Grips"] },                                         //itemNo: 'US PALM AK PISTOL GRIP BLACK'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Barrels",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Barrels"] },                                         //itemNo: 'BARREL SCAR 17S 308WIN 13"'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'BRUSHLINE PRO 2-7X32 1" BDC'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Trigger",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Triggers"] },                                         //itemNo: 'TRIGGER 2-STAGE STRAIGHT'} },
{ "itemGroup": "Double Action Centerfire Revolvers", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'MAGAZINE TAURUS 809 9MM 17RD #'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'BARREL TTS-22 22LR INTEG SUPP'} },
{ "itemGroup": "Double Action Centerfire Revolvers", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'BODYGUARD 380ACP 6+1 RED LASER'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Safety",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'AMBI SELECTOR SWITCH'} },
{ "itemGroup": "Double Action Rimfire Conceal Revolvers", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'LCRX 22LR BL/HOGUE 3" 8RD AS'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Slings and Swivels",
		"bc_path":  ["Firearms", "Shooting", "Shooting Accessories", "Slings & Swivels"] },                                         //itemNo: 'RECEIVER EXTENSION QD PLATE'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Muzzle Brakes",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Muzzle Brakes"] },                                         //itemNo: 'MUZZLE BRAKE 223/5.56 1/2X28'} },
{ "itemGroup": "Double Action Rimfire Revolvers", "type": "Accessory-Rails",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Rails"] },                                         //itemNo: 'M70 SCOPE MOUNT QD PICATINNY'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'MAGAZINE CW380/P380 7RD W/EXT'} },
{ "itemGroup": "Handgun Accessories", "type": "Accessory-Barrels",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Barrels"] },                                         //itemNo: 'BARREL TP9 SFX 9MM BLK TB'} },
{ "itemGroup": "Handgun Accessories", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'MOON CLIP LCR 9MM 3 PACK'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Assortment",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'ULTIMA-LUBE II LITE OIL 4 OZ'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Trigger",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'PIN SET AR STAINLESS'} },
{ "itemGroup": "Handgun Magazines", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'PT-22 22LR SS/LAVENDER 8+1'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'HEX WASP MICRO RED DOT 3.5MOA'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Grips",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Grips"] },                                         //itemNo: 'STARBURST AR15 GUNFIGHTER GRIP'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Kits",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'BUFFER SPRING AR15'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory - Parts",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'BUSHING WRENCH 1911 FS/CPCT BL'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Bolts",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'BOLT CARRIER ASSY 5.56MM BLACK'} },
{ "itemGroup": "Handgun Accessories", "type": "Accessory-Kits",
		"bc_path":  ["Firearms","Shooting","Shooting Accessories"] },                                         //itemNo: 'BARREL KIT SR22 22LR 3.5" THRD'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Uppers",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'RECEIVER UPPER AR15 ANODIZED'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Flash Hiders",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'FLASH HIDER A2 BIRDCAGE 5.56MM'} },
{ "itemGroup": "Handgun Magazines", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'SUPERSTOC CARB BUTTSTOCK BLK'} },
{ "itemGroup": "Handgun Accessories", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: '3-POSITION STOCK SP5 BLACK'} },
{ "itemGroup": "Lasers and Lights", "type": "Accessory-Lights",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'X300 ULTRA LED LGHT TAN 1000LM'} },
{ "itemGroup": "Lower Receivers", "type": "Rifle",
		"bc_path":  ["Firearms","Shooting","Gun Parts","Lowers"] },                                         //itemNo: 'LOWER RECEIVER AR-556 5.56MM'} },
{ "itemGroup": "Magnified Tactical Optic Mounts", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases", "Mounts"] },                                         //itemNo: 'PRECISION MOUNT 30MM/1" QD'} },
{ "itemGroup": "Magnified Tactical Optics", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'X3 TACTIX 1-8X24 30MM OT FDE'} },
{ "itemGroup": "Magnified Tactical Optics", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms","Shooting","Optics"] },                                         //itemNo: 'X1 TACTIX MAG3 MAGNIFIER'} },
{ "itemGroup": "Metal Frame Centerfire Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'SW1911 9MM 10+1 5" SS/WD AS'} },
{ "itemGroup": "Metal Frame Rimfire Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'SW22 VICTORY TRGT 22LR 5.5" MA'} },
{ "itemGroup": "Metal Frame Centerfire Conceal Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'DESERT EAGLE 1911 45ACP 3" SS'} },
{ "itemGroup": "Metal Frame Centerfire Pistols", "type": "Specialty Handgun",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: '110 PCS PISTOL 223REM 10.5" TB'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases"] },                                         //itemNo: 'MOUNTING PLATE #2 VP OR'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory - Parts",
		"bc_path":  ["Firearms","Shooting","Gun Parts"] },                                         //itemNo: 'GRIP-N-RIP 7.62 CHARGE HANDLE'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Braces",
		"bc_path":  ["Firearms","Shooting","Gun Parts"] },                                         //itemNo: 'TELESCOPIC BRACE APC10       #'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms","Shooting","Gun Parts","Stocks"] },                                         //itemNo: 'GHM9 GEN 2 STOCK FOLDING     #'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Grips",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Grips"] },                                         //itemNo: 'PISTOL GRIP BLACK'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Trigger",
		"bc_path":  ["Firearms","Shooting","Gun Parts","Triggers"] },                                         //itemNo: 'BFSIII HK-C1 TRIGGER HK 91/94'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Lights",
		"bc_path":  ["Misc"] },                                         //itemNo: 'SF123A LITHIUM 3VOLT BATT 12PK'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Knives",
		"bc_path":  ["Gear & Apparel", "Accessories", "Knives & Tools", "Knives"] },                                         //itemNo: 'FIELD KNIFE W/SAW BLACK PKG'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Barrels",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts", "Barrels"] },                                         //itemNo: 'THREAD CAP MARK 23'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Silencer Accessories",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'THREAD CAP P30/USP9T'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Range Bags",
		"bc_path":  ["Misc"] },                                         //itemNo: '1 PISTOL RANGE BAG'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Entrenching Tool",
		"bc_path":  ["Misc"] },                                         //itemNo: 'ENTRENCHING TOOL W/POUCH PKG'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Uppers",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Upper Receivers"] },                                         //itemNo: 'UPPER MK18 5.56MM RIS II BLK'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Bolts",
		"bc_path":  ["Misc"] },                                         //itemNo: 'BOLT CARRIER GROUP COMPLETE'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Binoculars",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Binoculars"] },                                         //itemNo: 'HARNESS BINOCULAR QR'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Rails",
		"bc_path":  ["Firearms","Shooting","Gun Parts","Rails"] },                                         //itemNo: 'MFR 13.5 M-LOK ASSEMBLY BLACK'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Cases",
		"bc_path":  ["Firearms", "Shooting", "Storage & Security", "Gun Cases"] },                                         //itemNo: 'THOMPSON VIOLIN CASE RIFLE'} },
{ "itemGroup": "Miscellaneous Accessories", "type": "Accessory-Kits",
		"bc_path":  ["Misc"] },                                         //itemNo: 'LOWER PARTS KIT'} },
{ "itemGroup": "Non-Magnified Optic Mounts", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases","Mounts"] },                                         //itemNo: 'MOUNT DELTAPT PRO CROSS SLOT'} },
{ "itemGroup": "Non-Magnified Optics", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms","Shooting","Optics"] },                                         //itemNo: 'X3 TACTIX ARD 2MOA RED DOT QD'} },
{ "itemGroup": "Over/Under Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Over & Under"] },                                         //itemNo: 'HUNTER MAG O/U 12/30 MODB 3.5"'} },
{ "itemGroup": "Polymer Centerfire Conceal Carry Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'CW9 9MM SS/BLK 3.6" 7+1'} },
{ "itemGroup": "Polymer Centerfire Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'M&P40 M2.0 PC PTD CORE 40S&W'} },
{ "itemGroup": "Polymer Rimfire Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'SR22 PISTOL 22LR 4.5" BL AS'} },
{ "itemGroup": "Pump Rimfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'GALLERY 22LR BL/WD 18" 15+1'} },
{ "itemGroup": "Range Finders", "type": "Accessory-Range Finders",
		"bc_path":  ["Firearms", "Shooting", "Optics","Binoculars","Range Finders"] },                                         //itemNo: 'RX-1600i TBR LASER RNGFNDR BLK'} },
{ "itemGroup": "Rifle Magazines", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories", "Magazines"] },                                         //itemNo: 'PROMAG RUGER 10/22 32RD'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases"] },                                         //itemNo: 'BASE ONE-PIECE OUTFITTER'} },
{ "itemGroup": "Rifle Magazines", "type": "Accessory-Uppers",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'MR556A1 UPPER RECEIVER 5.56MM'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Muzzle Brakes",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Muzzle Brakes"] },                                         //itemNo: 'RADIAL PORT MZZLE BRK 223/5.56'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Stocks",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Stocks"] },                                         //itemNo: 'FOLDING STOCK SP5K BLACK'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Magazines",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories","Magazines"] },                                         //itemNo: 'SECURITY9 COMPACT MAG ADAPTER'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Bolts",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'BOLT ASY DSRTEAG L5 44MAG/50AE'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Trigger",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Triggers"] },                                         //itemNo: 'ELITE 452 MSR TRIGGER 2 STAGE'} },
{ "itemGroup": "Rifle Magazines", "type": "Rifle",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories","Magazines"] },                                         //itemNo: 'M1 CARBINE 30CAL PARK/WD 15RD'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Rails",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts","Rails"] },                                         //itemNo: 'HANDGUARD 12" M-LOK BLACK'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory - Parts",
		"bc_path":  ["Firearms", "Shooting", "Gun Parts"] },                                         //itemNo: 'PROMAG VERTICAL FORE GRIP BLK'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Magazine Pouches",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'BX-MAGAZINE DUST COVER 3 PACK'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms", "Shooting", "Optics"] },                                         //itemNo: 'RAPID DEPLOY REAR SIGHT'} },
{ "itemGroup": "Rifle Accessories", "type": "Accessory-Magazine Release",
		"bc_path":  ["Firearms", "Shooting", "Magazines & Accessories"] },                                         //itemNo: 'EXTENDED MAG RELEASE 10/22'} },
{ "itemGroup": "Rifle/Shotgun Combos", "type": "Combo",
		"bc_path":  ["Firearms","Firearm Combos"] },                                         //itemNo: 'MOD 42 TKDN 22LR/410 BL/SY 20"'} },
{ "itemGroup": "Rimfire Silencers", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'SILENT-SR 22LR SILENCER 1/2x28'} },
{ "itemGroup": "Scope Mounts", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases","Mounts"] },                                         //itemNo: 'BASE QRW TIKKA T3X 2-PC MATTE'} },
{ "itemGroup": "Scope Rings", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases","Rings"] },                                         //itemNo: 'RING SET 30MM HIGH'} },
{ "itemGroup": "Scope Accessories", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'SCOPE COVER NEOPRENE XXL'} },
{ "itemGroup": "Scope Accessories", "type": "Accessory-Tools",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'LENS PEN'} },
{ "itemGroup": "Scope Mounts", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'RUGER-57 OAP BURRIS & VORTEX'} },
{ "itemGroup": "Scopes", "type": "Accessory-Lasers and Sights",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'FREEDOM RDS 1X34 BDC 1 MOA DOT'} },
{ "itemGroup": "Scopes", "type": "Accessory-Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'MARK 3HD 4-12X40MM ILL FD TMR'} },
{ "itemGroup": "Short Barrel Rifles", "type": "NFA - Short Barrel Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'THOMPSON M1 SBR 45CAL 10.5"'} },
{ "itemGroup": "Side by Side Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Side-by-Side"] },                                         //itemNo: 'BRISTOL SXS 12/28 BL/WD 3" CCH'} },
{ "itemGroup": "Silencer Accessories", "type": "Accessory-Silencer Accessories",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'OBSIDIAN FIXED BARREL SPACER'} },
{ "itemGroup": "Silencer Mounts", "type": "Accessory-Silencer Accessories",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'OBSIDIAN 3 LUG ADAPTER 1/2X28'} },
{ "itemGroup": "Silencer Pistons", "type": "Accessory-Silencer Accessories",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'OBSIDIAN PISTON M16X1 LH'} },
{ "itemGroup": "Silencer Mounts", "type": "Accessory-Flash Hiders",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'MUZZLE BRAKE QD 5.56MM 1/2X28'} },
{ "itemGroup": "Silencer Mounts", "type": "Accessory-Muzzle Brakes",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'DD WAVE MUZZLE BREAK 5/8X24'} },
{ "itemGroup": "Silencer Accessories", "type": "Accessory-Muzzle Brakes",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'RX BLAST DIVERTER/BRAKE BLACK'} },
{ "itemGroup": "Single Shot Centerfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'SCOUT CPT 6.5CR BK/SYN 20"'} },
{ "itemGroup": "Single Shot Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns"] },                                         //itemNo: 'TT-15 MONO TRAP 12/34 2.75"'} },
{ "itemGroup": "Single Action Centerfire Revolvers", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'BFR REVOLVER 357MAG SS 7.5"'} },
{ "itemGroup": "Single Action Rimfire Revolvers", "type": "Revolver",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'BEARCAT SHOPKEEPER 22LR 3" SS'} },
{ "itemGroup": "Single Action Rimfire Revolvers", "type": "Rifle",
		"bc_path":  ["Firearms", "Handguns", "Revolvers"] },                                         //itemNo: 'CRACKSHOT XBR 22LR BL/KRYPTEK'} },
{ "itemGroup": "Single Shot Centerfire Rifles", "type": "Muzzleloader",
		"bc_path":  ["Firearms","Shooting","Black Powder","Muzzleloader"] },                                         //itemNo: 'NITROFIRE 50CAL BRZ/RT EDGE'} },
{ "itemGroup": "Specialty Pistols", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'CHARGER LITE 22LR SYN 10" 15+1'} },
{ "itemGroup": "Sporting Bolt Action Rimfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: '457 VARMINT PRECISION 22LR 24"'} },
{ "itemGroup": "Sporting Semi-Auto Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Semi Auto"] },                                         //itemNo: 'MAXUS II WW MOOBL 12/26 3.5" #'} },
{ "itemGroup": "Sporting Bolt Action Centerfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Bolt Action"] },                                         //itemNo: 'XPR TH VARMINT SR 30-06 24"  #'} },
{ "itemGroup": "Sporting Semi-Auto Rimfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Semi Auto"] },                                         //itemNo: 'A22 22LR BL/LAM 22" T'HOLE STK'} },
{ "itemGroup": "Sporting Bolt Action Centerfire Rifles", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns"] },                                         //itemNo: '212 SLUG 12GA BOLT BL/SYN ACU'} },
{ "itemGroup": "Sporting Pump Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Pump Action"] },                                         //itemNo: '835 12/26 MOBL 3.5"'} },
{ "itemGroup": "Sporting Bolt Action Rimfire Rifles", "type": "Accessory-Rings/Mounts/Bases",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Rings, Mounts & Bases"] },                                         //itemNo: 'RASCAL SCOPE BASE KIT'} },
{ "itemGroup": "Sporting Leveraction Centerfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'M92 GOLD 44MAG BL/WD 20" 10+1'} },
{ "itemGroup": "Sporting Leveraction Rimfire Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles"] },                                         //itemNo: 'RIO BRAVO 22LR GLD/WD 18" 15+1'} },
{ "itemGroup": "Spotting Scopes", "type": "Accessory-Spotting Scopes",
		"bc_path":  ["Firearms", "Shooting", "Optics", "Scopes"] },                                         //itemNo: 'SX-2 ALPINE 20-60X80 ANGLED'} },
{ "itemGroup": "Synthetic Holsters", "type": "Accessory-Holsters",
		"bc_path":  ["Firearms", "Shooting", "Shooting Accessories", "Holsters"] },                                         //itemNo: 'HOLSTER RAPID DEPLOY RH BLACK'} },
{ "itemGroup": "Tactical Centerfire Semi-Auto Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Semi Auto"] },                                         //itemNo: 'DD5 V3 308WIN 16" MLOK CA COMP'} },
{ "itemGroup": "Tactical Pump Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Pump Action"] },                                         //itemNo: 'COBRA III TACT PUMP 12/18.5 3"'} },
{ "itemGroup": "Tactical Bolt Action Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Bolt Action"] },                                         //itemNo: '110 TACTICAL 6.5CR SYN 24" LH'} },
{ "itemGroup": "Tactical Centerfire Semi-Auto Rifles", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'BREN 2 MS PISTOL 5.56 BK 14"'} },
{ "itemGroup": "Tactical Rimfire Semi-Auto Rifles", "type": "Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Semi Auto"] },                                         //itemNo: 'M&P15-22 SPORT 22LR 10+1 COMP'} },
{ "itemGroup": "Tactical Semi-Auto Shotguns", "type": "Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Semi Auto"] },                                         //itemNo: 'RAPTOR ATAC 12/20 SYN 3"'} },
{ "itemGroup": "Tactical Pump Shotguns", "type": "NFA - Short Barrel Shotgun",
		"bc_path":  ["Firearms","Long Guns","Shotguns","Pump Action"] },                                         //itemNo: '590A1 12/14 PKZD 3" GHOST SGT'} },
{ "itemGroup": "Tactical Centerfire Semi-Auto Rifles", "type": "NFA - Short Barrel Rifle",
		"bc_path":  ["Firearms", "Long Guns", "Rifles", "Semi Auto"] },                                         //itemNo: 'SAINT EDGE SBR 5.56 11.5" 30+1'} },
{ "itemGroup": "Tactical Centerfire Semi-Auto Rifles", "type": "NFA - Silencer",
		"bc_path":  ["Firearms", "Shooting", "NFA/Class III", "Suppressors"] },                                         //itemNo: 'DDM4 ISR 300BLK MILSPEC+ 16"'} },
{ "itemGroup": "Tactical Rimfire Semi-Auto Rifles", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'M&P15-22 PISTOL 22LR 8" 25+1'} },
{ "itemGroup": "TACTICAL CENTERFIRE SEMI-AUTO PISTOLS", "type": "Semi-Auto Pistol",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'GHM9K PIST 9MM BLK 17+1      #'} },
{ "itemGroup": "TACTICAL CENTERFIRE SEMI-AUTO PISTOLS", "type": "NFA - Short Barrel Rifle",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'USW-A1 PIST 9MM BLK 4.3" 17+1#'} },
{ "itemGroup": "TACTICAL CENTERFIRE SEMI-AUTO PISTOLS", "type": "Rifle",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'PROTECTOR PIST 5.56MM 11.3" BK'} },
{ "itemGroup": "TACTICAL CENTERFIRE SEMI-AUTO PISTOLS", "type": "Specialty Handgun",
		"bc_path":  ["Firearms", "Handguns", "Pistols"] },                                         //itemNo: 'CA12 PISTOL 350LEG 12" 10+1'} },
];
    

/* misc constants needed for import / update processing */
const importOptions = {
    sku_tag: "bGlwc2V5cw",
    name_tag: "l",
    default_category_path: [ "Misc" ],
    image_url: "https://www.lipseyscloud.com/images/{ix}",
    image_url_ix: "{ix}",
    webdav_host: "https://sportsmans-finest.mybigcommerce.com",
    webdav_options: {
        authType: AuthType.Digest,
        username: "***",
        password: "***"
    },
    ftp_options: {
        host: "ftp.lipseysdistribution.net",
        user: "***",
        password: "***"
    },
    csvCustomFields: { // map CSV columns to be mapped to custom fields, with substitute name
        //"ItemNo": "ItemNo",
        //"Description1": "Description 1",
        //"Description2": "Description 2",
        //"Upc": "UPC",
        //"ManufacturerModelNo": "Manufacturer Model No",
        "Msrp": "Msrp",
        "Model": "Model",
        "CaliberGauge": "Caliber Gauge",
        //"Manufacturer": "Manufacturer",
        "Type": "Type",
        "Action": "Action",
        "BarrelLength": "Barrel Length",
        "Capacity": "Capacity",
        "Finish": "Finish",
        "OverallLength": "Overall Length",
        "Receiver": "Receiver",
        "Safety": "Safety",
        "Sights": "Sights",
        "StockFrameGrips": "Stock Frame Grips",
        "Magazine": "Magazine",
        //"Weight": "Weight",
        //"ImageName": "Image Name",
        "Chamber": "Chamber",
        "DrilledAndTapped": "Drilled and Tapped",
        "RateOfTwist": "Rate of Twist",
        "ItemType": "ItemType",
        //"AdditionalFeature1": "Additional Feature 1",
        //"AdditionalFeature2": "Additional Feature 2",
        //"AdditionalFeature3": "Additional Feature 3",
        //"ShippingWeight": "Shipping Weight",
        "BoundBookManufacturer": "Bound Book Manufacturer",
        "BoundBookModel": "Bound Book Model",
        "BoundBookType": "Bound Book Type",
        "NfaThreadPattern": "NFA Thread Pattern",
        "NfaAttachmentMethod": "NFA Attachment Method",
        "NfaBaffleType": "NFA Baffle Type",
        "SilencerCanBeDisassembled": "Silencer Can Be Disassembled",
        "SilencerConstructionMaterial": "Silencer Construction Material",
        "NfaDbReduction": "NFA DB Reduction",
        "SilencerOutsideDiameter": "Silencer Outside Diameter",
        "NfaForm3Caliber": "NFA Form 3 Caliber",
        "OpticMagnification": "Optic Magnification",
        "MaintubeSize": "Maintube Size",
        "AdjustableObjective": "Adjustable Objective",
        "ObjectiveSize": "Objective Size",
        "OpticAdjustments": "Optic Adjustments",
        "IlluminatedReticle": "Illuminated Reticle",
        "Reticle": "Reticle",
        "Exclusive": "Exclusive",
        //"Quantity": "Quantity",
        //"Allocated": "Allocated",
        //"OnSale": "On Sale",
        //"Price": "Price",
        "CurrentPrice": "Current Price",
        //"RetailMap": "Retail MAP",
        "FflRequired": "FFL Required",
        "SotRequired": "SOT Required",
        "ExclusiveType": "Exclusive Type",
        "ScopeCoverIncluded": "Scope Cover Included",
        "Special": "Special",
        "SightsType": "Sights Type",
        "Case": "Case",
        "Choke": "Choke",
        "DbReduction": "DB Reduction",
        "Family": "Family",
        "FinishType": "Finish Type",
        "Frame": "Frame",
        "GripType": "Grip Type",
        "HandgunSlideMaterial": "Handgun Slide Material",
        "CountryOfOrigin": "Country of Origin",
        //"ItemLength": "Item Length",
        //"ItemWidth": "Item Width",
        //"ItemHeight": "Item Height",
        "PackageLength": "Package Length",
        "PackageWidth": "Package Width",
        "PackageHeight": "Package Height",
        //"ItemGroup": "Item Group",
    }
    
}

exports.importOptions = importOptions;
exports.category_map = category_map;
